### ISSUE TITLE
Python Gives multiple errors

### ISSUE THREAD

**Issue by steelneel** [edonavon/mazak#1]
When I run the main.py I get multiple errors. I went through and debugged the file and found over 12 errors I tried to fix them and only got 4 fixed. I would really like to use this project to edit mazatrol. I don't know if anyone will ever see this, but this looked like a good idea,

**Comment by edonavon** [comment]
Hi,
I’m happy that you find it useful.
Can you send me your errors?

I also think I have more recent code… I will send you

Regards,
Edo

**Comment by steelneel** [comment]
Here is the debug log that I got when I run and debug it. I'm using ms visual studio code to debug it. 



PS C:\Users\steel\OneDrive\Desktop\mazak-master>  c:; cd 'c:\Users\steel\OneDrive\Desktop\mazak-master'; & 'C:\Users\steel\AppData\Local\Microsoft\WindowsApps\python3.8.exe' 'c:\Users\steel\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\launcher' '1061' '--' 'c:\Users\steel\OneDrive\Desktop\mazak-master\main.py' 
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\steel\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\steel\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\steel\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 239, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "c:\Users\steel\OneDrive\Desktop\mazak-master\main.py", line 227
    print "Z0=%s, X0=%s, X=%s, Z=%s, S_CNR=%s, F_CNR=%s"%(line[1], line[0]/2, line[2]/2, Length, line[4], line[5])
          ^
SyntaxError: invalid syntax
PS C:\Users\steel\OneDrive\Desktop\mazak-master> 


Thanks

If you could send me the newer code that would be fabulouse!

**Comment by steelneel** [comment]
Hey there did you ever find the newer code for the Masak editor? If not it’s alright. Thanks
